import bcrypt from "bcryptjs";
import type { DataStore } from "./domain";

const now = "2026-09-09T06:00:00.000Z";

export function buildSeedData(): DataStore {
  const passwordHash = bcrypt.hashSync("password", 10);

  return {
    tenants: [{ id: "tenant_k2", name: "K2 Wealth", status: "ACTIVE", createdAt: now }],
    users: [
      {
        id: "admin-1",
        tenantId: "tenant_k2",
        name: "Aditi Rao",
        email: "admin@k2wealth.com",
        phone: "+919900000001",
        role: "ADMIN",
        status: "ACTIVE",
        passwordHash,
        createdAt: now,
      },
      {
        id: "rm-3",
        tenantId: "tenant_k2",
        name: "Vikram Mehta",
        email: "manager@k2wealth.com",
        phone: "+919900000002",
        role: "MANAGER",
        status: "ACTIVE",
        passwordHash,
        createdAt: now,
      },
      {
        id: "rm-1",
        tenantId: "tenant_k2",
        name: "Rahul Sharma",
        email: "rahul@firm.com",
        phone: "+919900000003",
        role: "RM",
        status: "ACTIVE",
        passwordHash,
        createdAt: now,
      },
      {
        id: "rm-2",
        tenantId: "tenant_k2",
        name: "Priya Nair",
        email: "priya@firm.com",
        phone: "+919900000004",
        role: "RM",
        status: "ACTIVE",
        passwordHash,
        createdAt: now,
      },
      {
        id: "ops-1",
        tenantId: "tenant_k2",
        name: "Central Ops",
        email: "ops@k2wealth.com",
        phone: "+919900000005",
        role: "OPS",
        status: "ACTIVE",
        passwordHash,
        createdAt: now,
      },
    ],
    teamMemberships: [
      { id: "tm_rahul", tenantId: "tenant_k2", managerUserId: "rm-3", memberUserId: "rm-1" },
      { id: "tm_priya", tenantId: "tenant_k2", managerUserId: "rm-3", memberUserId: "rm-2" },
    ],
    clients: [
      {
        id: "cli-1",
        tenantId: "tenant_k2",
        name: "Vikramaditya Singhania",
        firmOrFamily: "Singhania Family Office",
        tier: "Ultra-HNWI",
        city: "Mumbai (Nariman Point)",
        phone: "+919811111111",
        assignedRmId: "rm-1",
        riskCategory: "Aggressive Growth",
        kycStatus: "Verified (Valid till 14-04-27)",
        aumNumeric: 285000000,
        createdAt: now,
      },
      {
        id: "cli-2",
        tenantId: "tenant_k2",
        name: "Sunita & Rajesh Goenka",
        firmOrFamily: "Goenka Family",
        tier: "HNWI CXO",
        city: "Bengaluru (Indiranagar)",
        phone: "+919822222222",
        assignedRmId: "rm-1",
        riskCategory: "Moderate Balanced",
        kycStatus: "Action Required (CAMS Re-KYC due 15-09-26)",
        aumNumeric: 84000000,
        createdAt: now,
      },
      {
        id: "cli-3",
        tenantId: "tenant_k2",
        name: "Dr. Ananya Iyer",
        firmOrFamily: "Dr. Iyer Surgical Clinic",
        tier: "Affluent",
        city: "Chennai (Adyar)",
        phone: "9800011003",
        assignedRmId: "rm-2",
        riskCategory: "High Growth",
        kycStatus: "Verified (Valid till 20-11-28)",
        aumNumeric: 32000000,
        createdAt: now,
      },
      {
        id: "cli-4",
        tenantId: "tenant_k2",
        name: "Kabir Malhotra",
        firmOrFamily: "FinTech Founder Office",
        tier: "Emerging Tech HNWI",
        city: "Gurugram (Golf Course Rd)",
        phone: "9800011004",
        assignedRmId: "rm-1",
        riskCategory: "Aggressive",
        kycStatus: "Verified",
        aumNumeric: 128000000,
        createdAt: now,
      },
    ],
    clientContextNotes: [
      { id: "note_1", clientId: "cli-1", note: "Second generation industrialist. Daughter studying at Wharton; Gurgaon sale will unlock ₹4.2 Cr.", source: "RM", updatedAt: now },
      { id: "note_2", clientId: "cli-2", note: "Retiring in 3 years. Extremely risk-sensitive; CAMS re-KYC blocker active.", source: "Compliance", updatedAt: now },
      { id: "note_3", clientId: "cli-3", note: "Chief Interventional Cardiologist. Avoid calls during 8 AM - 6 PM clinic hours.", source: "RM", updatedAt: now },
      { id: "note_4", clientId: "cli-4", note: "FinTech founder expects another ₹2.5 Cr payout in Q3.", source: "RM", updatedAt: now },
    ],
    clientRelationshipMoments: [
      { id: "moment_1", clientId: "cli-1", date: "2026-10-15", label: "Rhea's next Wharton tuition installment due" },
      { id: "moment_2", clientId: "cli-2", date: "2026-09-22", label: "Rajesh & Sunita's wedding anniversary" },
      { id: "moment_3", clientId: "cli-3", date: "2027-03-31", label: "Clinic financial year-end" },
      { id: "moment_4", clientId: "cli-4", date: "2026-09-30", label: "Expected secondary payout" },
    ],
    portfolioAllocations: [
      { id: "alloc_1_t", clientId: "cli-1", equityPct: 65, debtPct: 25, alternatesPct: 10, allocationType: "TARGET" },
      { id: "alloc_1_c", clientId: "cli-1", equityPct: 78, debtPct: 14, alternatesPct: 8, allocationType: "CURRENT" },
      { id: "alloc_2_t", clientId: "cli-2", equityPct: 50, debtPct: 40, alternatesPct: 10, allocationType: "TARGET" },
      { id: "alloc_2_c", clientId: "cli-2", equityPct: 42, debtPct: 48, alternatesPct: 10, allocationType: "CURRENT" },
      { id: "alloc_3_t", clientId: "cli-3", equityPct: 80, debtPct: 20, alternatesPct: 0, allocationType: "TARGET" },
      { id: "alloc_3_c", clientId: "cli-3", equityPct: 62, debtPct: 38, alternatesPct: 0, allocationType: "CURRENT" },
      { id: "alloc_4_t", clientId: "cli-4", equityPct: 70, debtPct: 15, alternatesPct: 15, allocationType: "TARGET" },
      { id: "alloc_4_c", clientId: "cli-4", equityPct: 71, debtPct: 16, alternatesPct: 13, allocationType: "CURRENT" },
    ],
    portfolioHoldings: [
      { id: "hold_1", clientId: "cli-1", name: "Parag Parikh Flexi Cap Fund - Direct", assetType: "Equity MF", valueNumeric: 68000000, valueDisplay: "₹6.80 Cr", returnDisplay: "+18.4% XIRR", sourceSystem: "WealthSpectrum" },
      { id: "hold_2", clientId: "cli-1", name: "Kotak Privy Savings (Idle Cash)", assetType: "Liquid", valueNumeric: 45300000, valueDisplay: "₹4.53 Cr", returnDisplay: "3.5% S.B.", sourceSystem: "Kotak Privy" },
      { id: "hold_3", clientId: "cli-2", name: "HDFC Corporate Bond Fund", assetType: "Debt MF", valueNumeric: 28500000, valueDisplay: "₹2.85 Cr", returnDisplay: "+7.8% XIRR", sourceSystem: "CAMS" },
      { id: "hold_4", clientId: "cli-3", name: "Kotak Emerging Equity Fund", assetType: "Mid Cap MF", valueNumeric: 11000000, valueDisplay: "₹1.10 Cr", returnDisplay: "+21.4% XIRR", sourceSystem: "BSE StAR MF" },
      { id: "hold_5", clientId: "cli-4", name: "Quant Active Fund - Direct", assetType: "Multi Cap", valueNumeric: 38000000, valueDisplay: "₹3.80 Cr", returnDisplay: "+24.5% XIRR", sourceSystem: "NSE NMF II" },
    ],
    clientOpportunities: [
      { id: "opp_1", clientId: "cli-1", type: "idle_cash", title: "₹45L Earning Sub-Inflation 3.5%", description: "Deploy into arbitrage fund via STP.", severity: "info", amountNumeric: 4500000, status: "open" },
      { id: "opp_2", clientId: "cli-2", type: "kyc", title: "Urgent: CAMS Re-KYC Pending", description: "Mutual fund folios may freeze unless Aadhaar OTP re-authentication is completed.", severity: "critical", amountNumeric: 0, status: "open" },
      { id: "opp_3", clientId: "cli-3", type: "idle_cash", title: "Equity 62% vs 80% Target Mandate", description: "Clinic surplus cash is dragging CAGR below target.", severity: "warning", amountNumeric: 2200000, status: "open" },
      { id: "opp_4", clientId: "cli-4", type: "liquidity", title: "Escrow Release Incoming (₹2.5 Cr)", description: "Prepare Pre-IPO / Cat II AIF commitment deck before funds arrive.", severity: "opportunity", amountNumeric: 25000000, status: "open" },
    ],
    tasks: [
      {
        id: "task-101",
        tenantId: "tenant_k2",
        clientId: "cli-1",
        title: "Arbitrage Deployment & STP Mandate (₹25 Lakhs)",
        details: "Move ₹25L idle savings into ICICI Prudential Arbitrage Fund with daily STP of ₹50,000 into Flexi Cap.",
        category: "Portfolio Rebalancing",
        priority: "High",
        status: "in_progress",
        assignedToUserId: "rm-1",
        assignedToName: "Rahul Sharma",
        slaDueAt: "2026-09-09T14:00:00.000Z",
        slaStatus: "near_breach",
        source: "Co-Pilot Recommendation",
        createdByUserId: "rm-1",
        idempotencyKey: null,
        createdAt: now,
        updatedAt: now,
      },
      {
        id: "task-102",
        tenantId: "tenant_k2",
        clientId: "cli-2",
        title: "Urgent CAMS Re-KYC & PAN-Aadhaar Resync",
        details: "Generate DigiLocker CAMS OTP re-KYC link. Ensure Rajesh validates PAN name mismatch.",
        category: "Compliance / KYC",
        priority: "Critical",
        status: "pending_ops",
        assignedToUserId: "ops-1",
        assignedToName: "Central Ops & Compliance",
        slaDueAt: "2026-09-09T16:30:00.000Z",
        slaStatus: "urgent",
        source: "Compliance Trigger (CAMS/KRA)",
        createdByUserId: "rm-1",
        idempotencyKey: null,
        createdAt: now,
        updatedAt: now,
      },
      {
        id: "task-103",
        tenantId: "tenant_k2",
        clientId: "cli-1",
        title: "Wharton LRS Outward Remittance (USD 85k / ₹71L)",
        details: "Form A2 and CA Certificate 15CB documentation for foreign education transfer via RBI LRS window.",
        category: "Banking / LRS",
        priority: "Urgent",
        status: "in_progress",
        assignedToUserId: "ops-1",
        assignedToName: "Central Ops & Compliance",
        slaDueAt: "2026-09-10T18:00:00.000Z",
        slaStatus: "on_track",
        source: "Client Request",
        createdByUserId: "rm-1",
        idempotencyKey: null,
        createdAt: now,
        updatedAt: now,
      },
      {
        id: "task-104",
        tenantId: "tenant_k2",
        clientId: "cli-4",
        title: "Tax-Loss Harvesting Review (Offset ₹4.5L STCG)",
        details: "Execute sale and instantaneous repurchase of loss-making ETF tranches to book tax loss before Q3 advance tax deadline.",
        category: "Tax Optimization",
        priority: "Medium",
        status: "pending_rm",
        assignedToUserId: "rm-1",
        assignedToName: "Rahul Sharma",
        slaDueAt: "2026-09-11T17:00:00.000Z",
        slaStatus: "on_track",
        source: "Co-Pilot Diagnostic",
        createdByUserId: "rm-1",
        idempotencyKey: null,
        createdAt: now,
        updatedAt: now,
      },
      {
        id: "task-105",
        tenantId: "tenant_k2",
        clientId: "cli-3",
        title: "WhatsApp Monthly Briefing & STP Consent (₹1.5L/mo)",
        details: "Dispatch 3-bullet WhatsApp portfolio update at 8:00 PM IST with BSE StAR MF one-click approval link.",
        category: "Client Review",
        priority: "Medium",
        status: "pending_rm",
        assignedToUserId: "rm-2",
        assignedToName: "Priya Nair",
        slaDueAt: "2026-09-09T20:00:00.000Z",
        slaStatus: "on_track",
        source: "Scheduled Review",
        createdByUserId: "rm-2",
        idempotencyKey: null,
        createdAt: now,
        updatedAt: now,
      },
      {
        id: "task-106",
        tenantId: "tenant_k2",
        clientId: "cli-1",
        title: "WhiteOak PMS Dividend Re-Investment Mandate",
        details: "Corporate action: re-invest ₹14.8L annual PMS dividend into growth allocation.",
        category: "Mandate Execution",
        priority: "Low",
        status: "completed",
        assignedToUserId: "rm-3",
        assignedToName: "Vikram Mehta",
        slaDueAt: "2026-09-13T12:00:00.000Z",
        slaStatus: "completed",
        source: "Cluster Head Mandate",
        createdByUserId: "rm-3",
        idempotencyKey: null,
        createdAt: now,
        updatedAt: now,
      },
    ],
    taskStatusHistory: [],
    taskAssignmentsHistory: [],
    callNotes: [],
    crmDrafts: [],
    crmLiquiditySignals: [],
    crmGeneratedTasks: [],
    crmSyncRecords: [],
    clientCommDrafts: [],
    auditLogs: [
      {
        id: "audit_1",
        tenantId: "tenant_k2",
        actorUserId: "rm-1",
        event: "task.created",
        clientId: "cli-1",
        taskId: "task-101",
        crmDraftId: null,
        detail: "Seed operations task created",
        complianceStatus: "ok",
        metadataJson: {},
        createdAt: now,
      },
    ],
    suitabilityChecks: [],
    houseViews: [
      {
        id: "hv-1",
        tenantId: "tenant_k2",
        title: "Global Equity & Macro Outlook",
        summary: "Our base case remains constructive on Indian equities over a 3-5 year horizon, driven by domestic consumption and capex.",
        tags: ["Equities", "Macro"],
        approvedBy: "Investment Committee",
        lastReviewedAt: now,
        status: "approved",
        version: 1,
        createdAt: now,
      },
      {
        id: "hv-2",
        tenantId: "tenant_k2",
        title: "Fixed Income & Interest Rate Trajectory",
        summary: "We favor high-quality short-to-medium duration debt over long-duration bets given rate uncertainty.",
        tags: ["Debt", "Rates"],
        approvedBy: "Investment Committee",
        lastReviewedAt: now,
        status: "approved",
        version: 1,
        createdAt: now,
      },
      {
        id: "hv-3",
        tenantId: "tenant_k2",
        title: "Geopolitical Risk & Portfolio Hedging",
        summary: "Maintain existing gold/alternates hedges per mandate and avoid reactive selling into single news events.",
        tags: ["Geopolitics", "Hedging"],
        approvedBy: "Investment Committee",
        lastReviewedAt: now,
        status: "approved",
        version: 1,
        createdAt: now,
      },
      {
        id: "hv-4",
        tenantId: "tenant_k2",
        title: "Gold & Alternates Allocation View",
        summary: "Maintain a 5-15% strategic allocation to gold and alternates as a portfolio stabilizer.",
        tags: ["Gold", "Alternates"],
        approvedBy: "Investment Committee",
        lastReviewedAt: now,
        status: "approved",
        version: 1,
        createdAt: now,
      },
    ],
    houseViewVersions: [
      { id: "hvv_1", houseViewId: "hv-1", summary: "Our base case remains constructive on Indian equities over a 3-5 year horizon, driven by domestic consumption and capex.", approvedBy: "Investment Committee", version: 1, effectiveAt: now },
      { id: "hvv_2", houseViewId: "hv-2", summary: "We favor high-quality short-to-medium duration debt over long-duration bets given rate uncertainty.", approvedBy: "Investment Committee", version: 1, effectiveAt: now },
      { id: "hvv_3", houseViewId: "hv-3", summary: "Maintain existing gold/alternates hedges per mandate and avoid reactive selling into single news events.", approvedBy: "Investment Committee", version: 1, effectiveAt: now },
      { id: "hvv_4", houseViewId: "hv-4", summary: "Maintain a 5-15% strategic allocation to gold and alternates as a portfolio stabilizer.", approvedBy: "Investment Committee", version: 1, effectiveAt: now },
    ],
  };
}
